server {
    server_name nas.nhotin.space;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Max upload size - Không giới hạn dung lượng tải lên
        client_max_body_size 0;

        # Hỗ trợ Websocket cho giao diện Synology DSM
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Tăng timeout tránh ngắt kết nối khi upload/download file lớn
        proxy_connect_timeout  36000s;
        proxy_read_timeout     36000s;
        proxy_send_timeout     36000s;
        send_timeout           36000s;
        
        # Tắt buffer để dữ liệu truyền trực tiếp không bị nghẽn ở Nginx
        proxy_buffering off;
        proxy_request_buffering off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/nhotin.space/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/nhotin.space/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = nas.nhotin.space) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name nas.nhotin.space;
    return 404; # managed by Certbot
}
